spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        enabled: false
  datasource:
    dynamic:
      primary: master #记得设置一个默认数据源，不设置的话默认为master
      datasource:
        master:   #master
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://xxxx:61859/jdxl_manage?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
          username: xx
          password: dev_baole123
          druid: #以下均为默认值
            initial-size: 3
            max-active: 8
            min-idle: 2
            max-wait: -1
            min-evictable-idle-time-millis: 30000
            max-evictable-idle-time-millis: 30000
            time-between-eviction-runs-millis: 0
            validation-query: select 1
            validation-query-timeout: -1
            test-on-borrow: false
            test-on-return: false
            test-while-idle: true
            pool-prepared-statements: true
            max-open-prepared-statements: 20
            filters: stat,wall
            share-prepared-statements: true
      #        jdxl_account:
      #          driver-class-name: com.mysql.jdbc.Driver
      #          url: jdbc:mysql://xxx:61859/jdxl_account?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
      #          username: dev_baole
      #          password: dev_baole123
      #          druid: #以下均为默认值
      #            initial-size: 3
      #            max-active: 8
      #            min-idle: 2
      #            max-wait: -1
      #            min-evictable-idle-time-millis: 30000
      #            max-evictable-idle-time-millis: 30000
      #            time-between-eviction-runs-millis: 0
      #            validation-query: select 1
      #            validation-query-timeout: -1
      #            test-on-borrow: false
      #            test-on-return: false
      #            test-while-idle: true
      #            pool-prepared-statements: true
      #            max-open-prepared-statements: 20
      #            filters: stat,wall
      #            share-prepared-statements: true
      mp-enabled: true


sharding.jdbc:
  enable: false
  biz:
    datasource:
      names: ds-master,ds-slave
      ds-master:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://xxx.com:61859/jdxl_account?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
        username: gameserver
        password: xx
        max-active: 8
        initial-size: 3
        min-idle: 3
        max-wait: 60000
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        test-while-idle: true
        test-on-borrow: true
        test-on-return: false
        validationQuery: SELECT 'x'
      ds-slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://xxx.com:61859/jdxl_account?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
        username: gameserver
        password: xx
        max-active: 8
        initial-size: 3
        min-idle: 2
        max-wait: 60000
        time-between-eviction-runs-millis: 60000
        min-evictable-idle-time-millis: 300000
        max-evictable-idle-time-millis: 3600000
        test-while-idle: true
        test-on-borrow: true
        test-on-return: false
        validationQuery: SELECT 'x'
    config:
      masterslave:
        load-balance-algorithm-type: round_robin
        name: ds_ms
        master-data-source-name: ds-master
        slave-data-source-names: ds-slave